import React, { useEffect, useState } from 'react'
import styled from '@emotion/styled'
import { useTheme } from '@itsrever/design-system'
import useSearchFinancialReport from '../../../hooks/useSearchFinancialReport'
import moment from 'moment'
import { formatPrice } from '../../../utils'
import device from '@/utils/device'
import { ReportsReportResponse } from '@itsrever/dashboard-api'

interface FinancialMetricsProps {
    report: ReportsReportResponse | undefined
}
const FinancialMetrics: React.FC<FinancialMetricsProps> = ({ report }) => {
    const theme = useTheme()

    // const { report } = useSearchFinancialReport('12', 2022)

    const moneyFormat = report?.money_format
    const grossSales =
        moneyFormat && formatPrice(report?.gross_sales || 0, moneyFormat)
    const discounts =
        moneyFormat && formatPrice(report?.discounts || 0, moneyFormat)
    const returnsToOpm =
        moneyFormat && formatPrice(report?.returns || 0, moneyFormat)

    const netSales =
        moneyFormat &&
        formatPrice(
            (report?.gross_sales || 0) +
                (report?.discounts || 0) +
                (report?.returns || 0),
            moneyFormat
        )

    const shipping =
        moneyFormat && formatPrice(report?.shipping || 0, moneyFormat)
    const taxes = moneyFormat && formatPrice(report?.taxes || 0, moneyFormat)
    const returnsByRever =
        moneyFormat &&
        formatPrice(
            (report?.rever_returns || 0) + (report?.rever_opm || 0),
            moneyFormat
        )
    const totalNetSales =
        moneyFormat &&
        formatPrice(
            (report?.gross_sales || 0) +
                (report?.discounts || 0) +
                (report?.returns || 0) +
                (report?.shipping || 0) +
                (report?.taxes || 0) +
                (report?.rever_returns || 0) +
                (report?.rever_opm || 0),
            moneyFormat
        )
    const reverSales =
        moneyFormat && formatPrice(report?.rever_net_sales || 0, moneyFormat)
    return (
        <MainDiv borderColor={theme.colors.grey[3]}>
            <GridDiv2>
                <h4>
                    <b>Concept</b>
                </h4>
                <h4 className="text-end">
                    <b>Value</b>
                </h4>
                <h4>
                    <b>Description</b>
                </h4>

                <p>Gross sales</p>
                <span className="text-end">{grossSales}</span>
                <p className="text-grey-2">Gross sales from Shopify</p>

                <p>Discounts</p>
                <span className="text-end">{discounts}</span>
                <p className="text-grey-2">Discounts applied from Shopify</p>

                <p>Refunds to original payment method</p>
                <span className="text-end">{returnsToOpm}</span>
                <p className="text-grey-2 ">
                    Gross returns from Shopify coming from original payment
                    method, manual refunds or cancellations
                </p>
                <hr className="col-span-3 m-0" />
                <h4>
                    <b>Net sales</b>
                </h4>
                <span className="text-end">
                    <b>{netSales}</b>
                </span>
                <p className="text-grey-2 ">Net sales from Shopify</p>

                <p>Shipping costs</p>
                <span className="text-end">{shipping}</span>
                <p className="text-grey-2 ">Shipping costs from Shopify</p>

                <p>Taxes</p>
                <span className="text-end">{taxes}</span>
                <p className="text-grey-2 ">Total taxes from Shopify</p>

                <p>Returns by REVER</p>
                <span className="text-primary-dark text-end">
                    {returnsByRever}
                </span>
                <p className="text-grey-2 ">
                    Total returns by REVER - Bank transfers, promo codes, gift
                    cards and exchanges.
                </p>
                <hr className="col-span-3" />
                <h4>
                    <b>Total Net sales</b>
                </h4>
                <span className="text-end">
                    <b>{totalNetSales}</b>
                </span>
                <p className="text-grey-2 ">The total of Net sales</p>
                <p>Coming from REVER</p>
                <span className="text-primary-dark text-end">{reverSales}</span>
                <p className="text-grey-2">
                    Part of total net sales generated by Exchanges, Promo codes
                    or Gift cards from REVER
                </p>
            </GridDiv2>
        </MainDiv>
    )
}

export default FinancialMetrics

interface BoxProps {
    borderColor: string
}

const GridDiv2 = styled.div`
    display: grid;
    grid-template-columns: 1.5fr 1fr 3fr;
    grid-template-rows: 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
    gap: 5px 40px;
    grid-template-areas:
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .'
        '. . .';
    width: 100%;
`

const MainDiv = styled.div<BoxProps>`
    border-radius: 0.5rem;
    border: 1px solid;
    border-color: ${(p) => p.borderColor};
    padding: 1.5rem;
    background-color: #fff;
    width: 100%;
`

const GridDiv = styled.div`
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: 0.5rem;
    align-items: center;
    width: fit-content;
`
