name: Cypress Tests using Cypress Docker

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PAT}}
      # Install YARN dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          browser: chrome
          start: yarn dev
          wait-on: http://localhost:3000/partner
          spec: 'cypress/e2e/spec.cy.ts'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PAT}}
          CYPRESS_RECORD_KEY:  ${{secrets.CYPRESS_RECORD_KEY}}
      # - name: 'Upload screenshots and videos to Slack'
      #   uses: trymbill/cypress-slack-video-upload-action@v1.3.0
      #   with:
      #     token: ${{ secrets.SLACK_TOKEN }}
      #     channels: "alerts"
      #     message-text: "Cypress tests failed! They have been placed in this thread, good luck."